### ISSUE TITLE
Отчёт о работе на семинаре 4

### ISSUE THREAD

**Issue by sarseniy** [GolAnd071/GolAnd071_Repo_001#1]
Привет!
Я пишу это в GitHub Issues. Здесь я буду оставлять комментарии о работе и вносить некоторые замечания к коду. Здесь же можно отвечать на мои вопросы и задавать свои касательно моих комментариев. Для простых вопросов, не связанных с конкретным Issue лучше обращаться в Telegram.

Так, это была общая часть, теперь касательно твоих рисунков.

1. Со смайликом всё ок, принято.
2. - С картинкой всё сложнее. Необходимо будет переделать это под реализацию через функции, тем более что в ДЗ надо будет сделать несколько копий уже существующих объектов.
    - Также есть некоторые недочёты в плане Code Style. Я конечно понимаю, что ты пишешь на плюсах в основном, но всё же.
![image](https://user-images.githubusercontent.com/70952998/134884586-7cdf5a29-4e9d-4485-be8e-a497445333bc.png)
Вот тут например необходим отступ в 2 пустые строчки между функциями.
![image](https://user-images.githubusercontent.com/70952998/134884775-487b7a1a-8e16-433d-a4ad-1d6ce612beaf.png)
А здесь слишком длинная строка, нужно переносить.
Таким образом, задание частично принято.

В общем, жду более сложную версию картинки с реализацией функций отрисовки объектов. Удачи!

UPD: руководство по Code Style https://www.python.org/dev/peps/pep-0008/

**Comment by GolAnd071** [comment]
Добрый вечер. В каком плане необходимо переделать под реализацию через функции? Мне надо рисование отдельных объектов разделить строчками и в комментариях подписать, что рисуется? Или ты хочешь облака с разными габаритами как функцию? Там не было особо повторяющихся объектов, кроме облаков и вещей, которые я рисовал циклами. Если нужно прямо-таки хоть что-то сделать функциями, я могу облака так сделать. Но это как-то странно. По сути облако и есть функция (ellipse). У меня на картинке нет каких-либо более сложных повторяющихся элементов (хотя бы из двух функций). Поэтому для такой картинки биение на функции мне кажется избыточным. Разбить на модули можно, но делать из них функции - как по мне, бесполезные строчки кода.

**Comment by GolAnd071** [comment]
И еще можно увидеть все предупреждения по PEP8, у меня VS2021 их не показывает.

**Comment by GolAnd071** [comment]
Обновление по кодстайлу: нашел в VS модули форматирования, прогнал по нему код, что получилось закоммитил. Про функции жду ответа, пока ничего не менял.

**Comment by sarseniy** [comment]
# Привет
## Я
### Могу
#### Писать
##### Вот
###### Так
Да, нужно параметризовать рисунок. Так, хочется видеть функцию для отрисовки отдельно домика, которая принимает координаты его левого нижнего угла (например) и, возможно, какой-то scale. Кроме того, на [усложнённой картинке](http://cs.mipt.ru/python/images/lab4/7_2.png "тык") (да, её нужно сделать) есть вот такие вот ребята.
![image](https://user-images.githubusercontent.com/70952998/135123759-4928c4c8-9ba5-4419-bc6c-1bd7a451dd7e.png)
Как здесь без scale и mirrow обойтись - бог его знает.

Про [PEP8](https://www.python.org/dev/peps/pep-0008/ "PEP8"), тут например необходимо разделит числа пробелами:
```python
polygon(screen, (255, 255, 0), [(100,100), (200,50), (300,100), (100,100)])
```
Вот так:
```python
polygon(screen, (255, 255, 0), [(100, 100), (200, 50), (300, 100), (100, 100)])
```
А вообще больше особых проблем то и не было. Можно конечно ещё поискать какой-нибудь [auto-restyler](http://pep8online.com/checkresult "вроде работает"), но это по факту такое себе.

В общем, эту тему можно закрывать, делай усложнённый рисунок.
