### ISSUE TITLE
Ошибка в конфигурации Гита

### ISSUE THREAD

**Issue by sarseniy** [GolAnd071/GolAnd071_Repo_001#2]
Смотри, у тебя в истории коммитов в качестве автора по идее должна быть кликабельная ссылка на твой профиль, но там вместо этого просто адрес почты. Проверь в настройках студии/гита правильность конфигурации почты/аккаунта/...
![image](https://user-images.githubusercontent.com/70952998/135149803-059e7dbb-2543-4592-81c8-238ce56f74ac.png)

**Comment by GolAnd071** [comment]
![image](https://user-images.githubusercontent.com/44880292/135156615-45b10197-8561-4e5f-9cbf-a6ed57e8cbc9.png)
Не факт, что она будет кликабельной

**Comment by sarseniy** [comment]
Факт -- не факт, но по идее должна быть таковой. Вот [пример](https://github.com/sarseniy/cpp_labs/commits/main "cpp_labs") или [вот](https://github.com/DGAP-clicker-2020/clicker/commits/main "clicker_game") ещё. Попробуй покопаться в настройках студии.

**Comment by GolAnd071** [comment]
Поправить историю с историей коммитов не вышло, запушил дз, почитай коммит, я там написал, что сделал все концептуально, не пытался прям в точности эту картинку повторить. Единственное - нет прозрачности. Все остальное (масштабирование дома, масштабирование и разворот по горизонтали призрака) есть.

**Comment by sarseniy** [comment]
Андрей, хорошо, я понял. Что же, будем надеяться, что история коммитов сама починиться (а что, а вдруг). Дз посмотрю позже. Тогда эта тема (но не проблема) закрыта.
