### ISSUE TITLE
Усложнённая картинка

### ISSUE THREAD

**Issue by sarseniy** [GolAnd071/GolAnd071_Repo_001#3]
Привет, вижу функции ты реализовал. Там всё хорошо. Немного неприятно отсутствие глаз у призраков... Хотелось бы что-то да вставить вместо чёрных кружков. Ещё немного напрягают вот эти вот HardCode цвета, их в принципе можно вынести наружу кода. Ну да ладно, это уже будет делать кто-то за тебя на следующей неделе. Задание принято, как прочитаешь -- можешь закрывать Issue.

**Comment by GolAnd071** [comment]
Ок

**Comment by sarseniy** [comment]
Хоть кто-то мне тут отвечает, ахахах

**Comment by GolAnd071** [comment]
Ну это вежливость что ли. Ну и привычка проверять почту)
